#43. Need to be correct. 16.10.17
DronMDF/telebot pull request #50
Opened 2017-10-16 19:10 UTC by sminux

Сейчас просто копипаст с https://stackoverflow.com/questions/41137742/syslog-parsing-using-pyparsing. В ближайшее время разберусь с парсером

2017-10-16 19:10 UTC, 0crat commented
@dronmdf please, pay attention to this pull request

2017-10-16 19:10 UTC, 0crat commented
Job `gh:dronmdf/telebot#50` is in scope.

2017-10-16 19:32 UTC, DronMDF commented
@sminux Наворочанно...
Скопипастил с SO? Это хорошо.
Если сам изобретал - можно было сделать проще.

Только вот файл я уже стер..
Ты должен посмотреть в первое сообщение в issue, там указан файл, в котором надо произвести изменение. Обнови свою ветку, и вставь код в tb/sources/syslog.py

Старайся, чтобы код имел смысл... Мы парсим логи для того, чтобы вернуть эту информацию.... Пусть от так или иначе ее возвращает. python'у пофиг, какой тип будет у этой информации до тех пор, пока мы не попытаемся ее получить.

2017-10-16 19:40 UTC, DronMDF commented on server.py
> +        return list1
@sminux Вполне подойдет, если ты эту функцию затащишь в SoSyslog.event(), хотя с ООП тут беда. :)

2017-10-16 19:44 UTC, DronMDF commented
Возможно я слишком требовательный. :)
Не забудь убрать todo...

2017-10-16 20:31 UTC, 0crat commented
Job `gh:dronmdf/telebot#50` assigned to @barbaragrape, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

2017-10-16 20:47 UTC, DronMDF requested changes
@sminux @BarbaraGrape 
Я тут подумал... Это не совсем правильно с точки зрения зерократии. Сейчас поясню.

В точке 1 - ты оставил недодлку, потому что код слишком сложен... Недоделок быть не должно. Ты должен минимальными усилиями сделать код, который возвращает результат. Который работает.

Но здесь слишком много парсинга. Парсинг в данном случае выглядит как оверинжениринг. Учитывая тот факто что мы не знаем точно какая информация нам интересна.

Поэтому правильными усилиями было бы - не думать на данном этапе о персинге и просто вернуть список строк... И на этом закрыть задачу. То есть класс Parser нужно выбросить, оставить одну функцию main, которую переместить в SoSyslog.actions(), которая вернет нераспарсенные строки.

В зерократии сама по себе заливка кода - это вызов. Вы это еще почувствуете немного попозже. Поэтому выбрасывайте все лишнее.

Сергей, тебе понятно что надо оставить и где?

2017-10-16 20:47 UTC, DronMDF commented on server.py
> +        ##need to be correct!!!
Точка номер 1

2017-10-16 20:47 UTC, DronMDF commented on server.py
> +            fields = parser.parse(line)
точка номер 2

2017-10-23 07:09 UTC, DronMDF commented
@sminux Спасибо, что уделяешь время, но у тебя по прежнему старая версия репозитория.
Давайте на занятии я постараюсь прояснить. А потом помогу тебе выбросить отсюда все лишнее. :)
У тебя опять остался закомментированный код, и это плохо.

2017-10-23 15:14 UTC, closed without merging

2017-11-13 12:41 UTC, DronMDF commented
@0crat out

2017-11-13 12:43 UTC, 0crat commented
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/50#issuecomment-343907481))

@DronMDF @barbaragrape resigned from `gh:dronmdf/telebot#50`, since the job is not in scope anymore.

2017-11-13 12:43 UTC, 0crat commented
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/50#issuecomment-343907481))

@DronMDF Job `gh:dronmdf/telebot#50` is now out of scope.