#37 bot.getUpdates #43 syslog messages
DronMDF/telebot pull request #54
Opened 2017-10-23 19:33 UTC by sminux

2017-10-23 19:33 UTC, 0crat commented
@dronmdf please, pay attention to this pull request

2017-10-23 19:34 UTC, 0crat commented
Job `gh:dronmdf/telebot#54` is in scope.

2017-10-23 20:06 UTC, DronMDF requested changes
Сейчас я внесу изменения.
И никогда не надо делать два изменения в одном коммите. Это плохо. Если по серьезному - то тебя могли бы попросить поделить его на два.

2017-10-23 20:06 UTC, DronMDF commented on tb/sources/syslog.py
> +		with open('./messages.txt') as syslogFile:
python очень чувствителен к форматированию.
Отступы надо делать одинаковой ширины.

2017-10-23 20:17 UTC, merged

2017-10-24 15:37 UTC, 0crat commented
Job `gh:dronmdf/telebot#54` assigned to @olejka, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

2017-10-24 15:43 UTC, DronMDF commented
@yegor256 This is closed merge request. 19 hours ago. Too late.

The distribution of the review is not very interesting to me now. Students... :)

2017-11-04 08:37 UTC, DronMDF commented
@0crat out

2017-11-04 08:38 UTC, 0crat commented
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/54#issuecomment-341880955))

@DronMDF @olejka resigned from `gh:dronmdf/telebot#54`, since the job is not in scope anymore.

2017-11-04 08:38 UTC, 0crat commented
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/54#issuecomment-341880955))

@DronMDF Job `gh:dronmdf/telebot#54` is now out of scope.